require "test_helper"

class UserTest < ActiveSupport::TestCase
  #generated by rails authentication
  #tests for the email's normalisation
  test "downcases and strips email_address" do
    user = User.new(
      name: "DOWNCASED",
      email_address: " DOWNCASED@EXAMPLE.COM ",
      password: "Password1234!"
      )
    assert_equal("downcased@example.com", user.email_address)
  end

  test "valid user" do
    user = users(:client_one)
    assert user.valid?
  end

  test "requires a name" do
    user = users(:client_one)
    user.name = nil
    assert_not user.valid?
  end

  test "requires unique email address" do
    duplicate = User.new(
      name: "Duplicate",
      email_address: users(:client_one).email_address,
      password: "Password1234!"
    )
    assert_not duplicate.valid?
  end

  test "requires valid role" do
    user = users(:client_one)
    user.role = "hacker"
    assert_not user.valid?
  end

   test "password must be at least 8 characters" do
    user = User.new(
      name: "Weak",
      email_address: "weak@example.com",
      password: "short1"
    )

    assert_not user.valid?
  end

  test "role helper methods work" do
    assert users(:client_one).client?
    assert users(:freelancer_one).freelancer?
    assert users(:admin).admin?
  end
end
